<a href="https://colab.research.google.com/github/plaupla/MachineLearningHealthFraudTest/blob/main/BPJSfraud2log_Obtain_model_predictions_predict_label_%3D_model_predict(X_test)reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving fraud_detection_train_int.csv to fraud_detection_train_int.csv


In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
import numpy as np
from pprint import pprint as pp
import csv
from pathlib import Path
import seaborn as sns
from itertools import product
import string

from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import BorderlineSMOTE
from imblearn.pipeline import Pipeline 

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score, classification_report, confusion_matrix, accuracy_score, roc_auc_score, roc_curve, precision_recall_curve, average_precision_score
from sklearn.metrics import homogeneity_score, silhouette_score
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.preprocessing import MinMaxScaler


/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [25]:
#set data
df = pd.read_csv("fraud_detection_train_int.csv")

In [27]:
print(df)

        visit_id  kdkc  dati2  umur  ...  proc80_99  proce00_e99  procv00_v89  label
0              1  1107    150    64  ...          0            0            0      1
1              2  1303    200    45  ...          4            0            0      1
2              3  1114    172    34  ...          0            0            0      1
3              4   601     90    34  ...          0            0            0      1
4              5  1006    130    27  ...          0            0            0      1
...          ...   ...    ...   ...  ...        ...          ...          ...    ...
200212    200213  2102    353    48  ...          1            0            0      0
200213    200214  1308    212     1  ...          0            0            0      0
200214    200215   201     38     3  ...          0            0            0      0
200215    200216  1008    128    52  ...          1            0            0      0
200216    200217  1016    117     4  ...          0            0 

In [26]:
#preprocess data
def prep_data(df: pd.DataFrame) -> (np.ndarray, np.ndarray):
  
    X = df.iloc[:, :-1].values 
    y = df.label.values
    return X, y

In [28]:
X, y = prep_data(df)

In [29]:
# Create the training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [30]:
# Fit a logistic regression model to our data
model = LogisticRegression(solver='liblinear')
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
# Obtain model predictions
predict_label = model.predict(X)

In [32]:
print(predict_label)

[1 1 1 ... 0 0 0]


In [33]:
predict_label.shape


(200217,)

In [35]:
print('Classification report:\n', classification_report(y, predict_label))
conf_mat = confusion_matrix(y_true=y, y_pred=predict_label)
print('Confusion matrix:\n', conf_mat)

Classification report:
               precision    recall  f1-score   support

           0       0.82      0.92      0.86     99962
           1       0.91      0.79      0.85    100255

    accuracy                           0.86    200217
   macro avg       0.86      0.86      0.86    200217
weighted avg       0.86      0.86      0.86    200217

Confusion matrix:
 [[91788  8174]
 [20654 79601]]


In [36]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y, predict_label, multioutput='raw_values')

array([0.14398378])

In [38]:
mean_absolute_error(y, predict_label)

0.1439837776013026

In [15]:
predict_label = pd.DataFrame(predict_label, columns=['predict_label']).to_csv('prediction.csv')

In [16]:
from google.colab import files

files.download('prediction.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>